#!/usr/bin/env bash

# Prepare the container
if [ ! -d /.composer ]; then
    mkdir /.composer
fi
mkdir /var/log/php-fpm/
chmod -R ugo+rw /.composer

# Prepare SSL on the container
chmod +x /opt/scripts/make-localhost-cert
/opt/scripts/make-localhost-cert /var/www/localhost.crt

# Prepare custom nginx files
mkdir -p /var/www/html/nginx.d/
cp -f /var/www/html/nginx.d/php-fpm.conf /etc/php/8.0/fpm/pool.d/www.conf 2>/dev/null
cp -f /var/www/html/nginx.d/nginx.conf /etc/nginx/sites-available/default 2>/dev/null
cp -f /var/www/html/nginx.d/nginx-ssl.conf /etc/nginx/sites-enabled/default-ssl 2>/dev/null
cp -f /var/www/html/nginx.d/php.ini /etc/php/8.0/fpm/php.ini 2>/dev/null
cp -f /var/www/html/nginx.d/php.ini /etc/php/8.0/cli/php.ini 2>/dev/null

# Moving potential supervisor files
if test -d /var/www/html/supervisor.d/; then
    cp -r /var/www/html/supervisor.d/* /etc/supervisor/conf.d/
fi

# Setting web application permissions
chown -R www-data:www-data /var/www/html

find /var/www/html/ -type f ! -path '*.sh' ! -path '/var/www/html/console' -exec chmod 644 {} +
find /var/www/html/ -type d -exec chmod 755 {} +

# Prep the cron.d directory
mkdir -p /var/log/html/cron.d/
chmod o+rwx /var/www/html/cron.d/*.sh
find /var/www/html/cron.d -type f ! -path '*.sh' -delete

# Process web app startup specifics
if test -e /var/www/html/docker.d/; then
    chmod o+rwx /var/www/html/docker.d/*.sh
    
    for file in /var/www/html/docker.d/*.sh; do
        filename=$(basename "$file")
        "$file" >> /var/log/"$filename".log 2>&1
    done
fi

# Start the container services
/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

exit